name: ml-playground
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - seaborn
      - scikit-learn
      - tensorflow
      - tensorflow-datasets
      - tensorflow-hub
      - opencv-python
      - jupyterlab
      - notebook
      - flask
      - fastapi
      - uvicorn
      - pillow
